### ISSUE TITLE
Generation issues (resulting in quality degradation) when using tokenizers with both hex and string representation of a token

### ISSUE THREAD

**Issue by andrejonasson** [Dan-wanna-M/formatron#19]
**Description**
I have observed quality degradation when using `formatron` for generation in comparison with no formatron. I suspect this applies to cases where both the hex representation and string representation exist in the tokenizer's vocabulary e.g. "<0x65>" ("e") and "e".

**Reproduce**
1. Choose model with tokenizer with both representations (e.g. Mistral family)
2. Generate JSON with and without formatron.
3. Observe difference in token ids that are generated. Hex tokens are generated in higher degree for formatron.

**Before and after applying formatron to Locutusque/TinyMistral-248M (has issue)**
Locutusque/TinyMistral-248M has both representations and has this issue.

without formatron:
```
['▁{"', 'review', '_', 'summary', '":"', 'A', '▁bit', '▁of', '▁an', '▁emotional', '▁roll', 'er', '▁co', 'aster', '","', 'm', 'ovie', '":"', 'U', 'gly', ',', '▁Dis', 'cipl', 'ined', '▁A', 'ctor', '▁(', '1', '9', '8', '7', ')', '▁Season', '▁', '9', ',', '▁Episode', '▁', '2', '6', '"}']
```
![image](https://github.com/user-attachments/assets/b2a2963a-4f3a-4b80-afa8-0edc90afbfe7)

with formatron (we use an altered grammar with a space at the start, we get similar generations with or without our alteration):
```
['▁{"', 'review', '<0x5F>', 'summary', '":"', 'The', '▁Big', '▁Bad', '▁F', 'ell', '.', '▁And', '▁It', '▁F', 'ell', '.', '","', 'mov', 'i', '<0x65>', '":"', 'Don', "'", '\x80', '\x99', '▁Che', 'ek', '▁(', '1', '9', '9', '2', ')', '▁unable', '▁to', '▁reach', '▁the', '▁halfway', '▁point', "''", '\x80', '\x9d']
```
![image](https://github.com/user-attachments/assets/ff85886d-3dcd-4ff3-81b0-db3ef8db2568)

**Before and after applying formatron to microsoft/phi-1_5 (does not seem to have an issue)**
microsoft/phi-1_5 does _not_ have both representations and seems to have no issue.

without formatron:
```
['Ġ{"', 'review', '_', 'summary', '":"', 'Too', 'Ġslow', 'Ġand', 'Ġbad', '.","', 'movie', '":"', 'L', 'iver', 'Ġ(', '1980', ')"', '}']
```
![image](https://github.com/user-attachments/assets/d6078d4e-a33d-4621-9d08-007453f45dd7)

with formatron:
```
['Ġ{"', 'review', '_', 'summary', '":"', 'Not', 'Ġas', 'Ġbad', 'Ġas', 'Ġit', 'Ġseems', '","', 'movie', '":"', 'K', 'rypt', 'on', 'Ġ(', 'I', ')', 'Ġ(', '2009', ')"', '}', 'Ċ']
```
![image](https://github.com/user-attachments/assets/1c13a776-abbf-46c8-97e8-e600e792e181)

Example tokenizers with both hex and string representation of same token (this applies to e.g. Mistral tokenizers):
TinyMistral-248M: https://huggingface.co/Locutusque/TinyMistral-248M/blob/main/tokenizer.json
Mistral-7b-v0.3: https://huggingface.co/mistralai/Mistral-7B-v0.3/raw/main/tokenizer.json

**Comment by Dan-wanna-M** [comment]
> both the hex representation and string representation exist
@andrejonasson Yes, more generally, when the same bytes are represented by two token ids. The previous formatron implementation will overwrite the existing token id(hence the hex representation appear rather than the normal representation.) Could you check out whether the latest commit fix the problem?

**Comment by andrejonasson** [comment]
@Dan-wanna-M It's looking much better. See below for stats/generations updated when applying commit with fix.

I am getting a large amount of warnings like so:
```
Token ID 71 and token ID 28757 corresponds to the same token. 
                        The second token ID will be ignored when matching tokens to ids. 
                        While matching tokens to ids is only used for debugging, 
                        seeing this warning likely indicates either input parameters are not created correctly 
                        or you are using a very creepy vocabulary.
```
Imo it might make sense to move it outside the loop and only warn once about all tokens in a single warning in `kbnf`. I can do another PR on `kbnf` to adjust it if desirable (I have been meaning to learn some basic rust, might be a good start).

>While matching tokens to ids is only used for debugging
So the warning is saying there is no practical implication? E.g. let's say a grammar can be followed by generating either token id, will both be possible to generate (e.g. imagine part of a grammar "ee" can it be completed with both "ee" and "<0x65>e" and so forth or will only a single token id be possible for "e").

Thanks.

**Before and after applying formatron to Locutusque/TinyMistral-248M (previously had issue) after fix **
Without formatron:
```
['▁{"', 'review', '_', 'summary', '":"', 'Review', '","', 'm', 'ovie', '":"', 'The', '▁C', 'ove', '▁(', '1', '9', '3', '5', ')"', '}']
```
![image](https://github.com/user-attachments/assets/11581606-5391-4896-97eb-bdefe52d6eea)

With formatron:
```
['▁{"', 'review', '_', 'summary', '":"', 'W', 'onder', 'ful', '▁and', '▁scary', ',', '▁but', '▁the', '▁best', '▁part', '▁of', '▁it', '▁is', '▁all', '▁too', '▁familiar', '","', 'm', 'ovie', '":"', 'Do', 'ctor', '▁Who', '▁(', '2', '0', '2', '2', '–', '2', '0', '2', '3', ')"', '}', '<0x0A>']
```
![image](https://github.com/user-attachments/assets/a2288d29-42f3-41f1-879d-f6de097f2843)

`<0x0A>` (newline) is generated at the end after `}` for pretty much all cases. It could lead to a (small) speedup in shorter generations by considering the json grammar complete at `}`.

**Comment by Dan-wanna-M** [comment]
> Imo it might make sense to move it outside the loop and only warn once about all tokens in a single warning in kbnf. I can do another PR on kbnf to adjust it if desirable (I have been meaning to learn some basic rust, might be a good start).

@andrejonasson Sure, feel free to go ahead. I believe your suggested change is doable for someone trying to learn some basic Rust. 

> E.g. let's say a grammar can be followed by generating either token id, will both be possible to generate

Yes, both tokens are possible. The warning was written as a sanity check because usually the map from token id to the actual bytes  is bijective. If it is not, then it might indicate something is subtly wrong in the vocabulary loading code. This will be very difficult for a user to debug, so I put an explicit warning here. In the context of Mistral(or Llama2 vocabulary in general) though, I think the duplicate tokens are just an inevitable consequence of the vocabulary that we have to live with. 

> <0x0A> (newline) is generated at the end after } for pretty much all cases.

I think you are using `append_line`? `append_line` by definition always requires the model to output a newline character at the end of generation(hence append "line",) You can try `append_str` which enforce the exact format string you pass in. Note that token healing issues may still require you to add some kinds of whitespaces to make the model "more familiar" with your output and hence generate better quality json.

**Comment by Dan-wanna-M** [comment]
Close it since the original issue(generation quality issue) is already resolved.
