### ISSUE TITLE
Issue when Import Schema on Mac OS

### ISSUE THREAD

**Issue by remichu-ai** [Dan-wanna-M/formatron#20]
Hi,

I am encounter this this error when importing Schema class on Mac Os.
Would like to know if this is fixable or you dont have plan to support Mac Os at the moment.

```
from formatron.schemas.pydantic import Schema
```

Error:
```
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
Cell In[9], line 1
----> 1 from formatron.schemas.pydantic import Schema

File ~/miniconda3/envs/mlenv/lib/python3.11/site-packages/formatron/schemas/__init__.py:8
      6 from . import pydantic
      7 from . import dict_inference
----> 8 from . import json_schema

File ~/miniconda3/envs/mlenv/lib/python3.11/site-packages/formatron/schemas/json_schema.py:16
     14 import jsonschema
     15 from formatron import schemas
---> 16 from referencing import Registry, Resource
     18 class FieldInfo(schemas.schema.FieldInfo):
     19     __slots__ = ("_annotation",)

ModuleNotFoundError: No module named 'referencing'
```

**Comment by Dan-wanna-M** [comment]
@remichu-ai I do not have a MacOS computer so I currently cannot test `formatron` on MacOS. That said, I do not use any OS-specific library so I do not expect it to break due to operating system differences. Could you try `pip install referencing`? It should already be installed as a necessary dependency of `jsonschema`, but maybe something unknown went wrong.

**Comment by remichu-ai** [comment]
@Dan-wanna-M , you are right that issue gone after i explicitly install `referencing`. Though, not why it was not installed even when i run `pip install -U formatron`

I will close the issue, however, do consider to explicitly include this as dependency if need to.
